### ISSUE TITLE
Article about using XD as a collaborative tool for open design

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#102]
I'm interested in what we can do in regards to how we use Adobe XD as a collaborative tool and why we (at Ushahidi) choose this tool as our primary.

This is largely an investigation into the 'sticker sheet' that will be available at the events and why/how we propose the creation and facilitation of these for other OSS projects

**Comment by klickass** [comment]
1. XD not Xd :) *important* /@thesocialdetail 
2. Let's discuss in a separate meeting as this includes heavy portions of roadmap/up-and-coming functionality

**Comment by Erioldoesdesign** [comment]
Make more focussed on the 'sticker sheet' or 'design system'

Instructions on how to use XD for contributing to TenFour

**Comment by Erioldoesdesign** [comment]
Immediate review needed! 

Unless thee are huge, mega errors or miscommunication I'd like to get this out asap.

@klickass @thomaskueber 

https://docs.google.com/document/d/1Dtk2J6dnYCfhXUpcXAqvErlK2LbUakM9-d9gb0myloM/edit?usp=sharing

**Comment by klickass** [comment]
First pass done
