### ISSUE TITLE
Add 'events' coming soon section to the website

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#106]
Based off feedback, visitors to the website are unsure what the direct/immediate aims of Open Design are.

I'd like to add a section to the main page that states we're having events. We don't have to communicate concrete dates at present but 'coming soon in 2019' is sufficient and the locations.

We need to achieve this with the current components on our site.

**Comment by Erioldoesdesign** [comment]
Thoughts on how to achieve this @vbhv would be awesome! :)

**Comment by vbhv** [comment]
Perhaps with a banner? @Erioldoesdesign

**Comment by Erioldoesdesign** [comment]
I think there's now the ability to add in an image into a section in the wordpress backend but it'd have to be investigated. 

please feel free to test in a draft page in wordpress if you'd like @vbhv

**Comment by vbhv** [comment]
Cool. Is there a doc with the event details? I can mock a banner using the design system you developed. Can't find it though @Erioldoesdesign

**Comment by Erioldoesdesign** [comment]
Design system file can be found here: https://drive.google.com/open?id=1aKhyOOCgzjxq-gEvH_eM1XlJxlCgN-Sn

I recommend banners on each individual page: https://opendesign.ushahidi.com/bangalore-1/
