### ISSUE TITLE
Hotjar feedback tab

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#109]
Can I get some folks to test whether they see the HotJar feedback tab on the side of the website?

![Screenshot 2019-08-26 at 14.07.50.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/3a944b42-28a3-4fbd-91d4-d991cff2e93c)

If yes, let's see if we can get this removed @thesocialdetail

**Comment by Erioldoesdesign** [comment]
It covers up content in mobile view:[Uploading... Screenshot 2019-08-26 at 14.08.52.png ]

**Comment by thesocialdetail** [comment]
Turn the feature off
