### ISSUE TITLE
FOSS4G Open Design talk slides

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#115]
You can view the .pdf version of the talk slide here:

https://www.slideshare.net/EriolFox/open-design-foss4-g-2019eriolfoxoperaroom3pm-1-168366007

And with speaker notes (if you download the file):

https://www.slideshare.net/EriolFox/open-design-foss4-g-2019eriolfoxoperaroom3pm-1

**Comment by klickass** [comment]
Lovely!
