### ISSUE TITLE
August social media report 

### ISSUE THREAD

**Issue by thesocialdetail** [ushahidi/opendesign#117]
[https://app.zenhub.com/files/179710835/18166aa2-9260-45d6-ba07-5b372f3b3b35/download](https://app.zenhub.com/files/179710835/18166aa2-9260-45d6-ba07-5b372f3b3b35/download)[https://app.zenhub.com/files/179710835/0e071220-c7bb-45f0-bfe2-b7708a492cb8/download](https://app.zenhub.com/files/179710835/0e071220-c7bb-45f0-bfe2-b7708a492cb8/download)

**Comment by Erioldoesdesign** [comment]
@thesocialdetail these files aren't working?

**Comment by thesocialdetail** [comment]
Tryin to upload again

[osd_facebook_2019-08-01_to_2019-08-31_created_on_20190903T1556Z.pdf](https://github.com/ushahidi/opendesign/files/3574911/osd_facebook_2019-08-01_to_2019-08-31_created_on_20190903T1556Z.pdf)
[osd_twitter_2019-08-01_to_2019-08-31_created_on_20190903T1558Z.pdf](https://github.com/ushahidi/opendesign/files/3574912/osd_twitter_2019-08-01_to_2019-08-31_created_on_20190903T1558Z.pdf)

**Comment by thesocialdetail** [comment]
Transferred to a new issue
