### ISSUE TITLE
Add new pages for past events

### ISSUE THREAD

**Issue by klickass** [ushahidi/opendesign#118]
Create new pages for Berlin and Seattle events. Compare #111.

**Comment by Erioldoesdesign** [comment]
These two pages now exist and are linked up in relevant pages:
https://opendesign.ushahidi.com/berlin-1/
https://opendesign.ushahidi.com/seattle-1/


-[] They need a brief summary of the past event.
-[] What were the challenges/briefs
-[] Links to external articles of the events
-[] Photos of participants
-[] Outputs - what was created by the teams
-[] What we changed going forward
-[] Contact us email link

**Comment by klickass** [comment]
Beefed up both pages but didn't add a couple of the things above – as I feel that is redundant/described in the external articles already.

Unsure about the contact us email link – is this is a template/block I am supposed to use?

**Comment by Erioldoesdesign** [comment]
@klickass Not sure what you mean by the contact us link can you do a screenshot?

**Comment by klickass** [comment]
I believe it is part of the page template and got added automatically. See attached. Feel free to reopen if you meant something different.

![Screenshot 2019-09-11 at 16 09 26](https://user-images.githubusercontent.com/2110595/64704470-a50cfa80-d4ae-11e9-9b35-34b467bf1e7c.png)

**Comment by Erioldoesdesign** [comment]
Ah thats our global footer...i don't think you can turn it off but you could add in a horizontal break line module to make it seem seperate!
