### ISSUE TITLE
Share buttons for articles

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#119]
Investigate plugins for social share. 

Needed for content KPIS.

**Comment by Erioldoesdesign** [comment]
Looks like this at the bottom of pages:

![Screenshot 2019-09-18 at 16.18.45.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/a838d4fc-1197-4314-983e-6619f24d870c)

Configurable via the plugin section from wordpress:

![Screenshot 2019-09-18 at 16.20.25.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/c58fcf3c-a54a-4adb-b395-889940371c61)

TBC on Analytics info. @thesocialdetail 

Facebook needs to have an app created to count the share. Facebook pixel ID?

**Comment by thesocialdetail** [comment]
Connected the Facebook API app still working one showing other platforms.

**Comment by Erioldoesdesign** [comment]
@thesocialdetail was there something you were looking into for this?

**Comment by thesocialdetail** [comment]
Can close this out. I was not able to find a way for the share counts to show with the Sassy Social plugin. The share count only shows for Facebook.
