### ISSUE TITLE
Live Tweet from Design Matters

### ISSUE THREAD

**Issue by thesocialdetail** [ushahidi/opendesign#136]
Live tweet from Design Matters conference 
handle @ designmattersdk
Event hashtag #designmatters19
https://designmatters.io

**Comment by Erioldoesdesign** [comment]
I did a few tweets
![Screenshot 2019-09-24 at 10.02.34.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/ae1a8fd8-07fe-409a-ab5c-f6dc2aab5add)

![Screenshot 2019-09-24 at 10.05.14.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/623d624b-1e4c-41b8-8575-66cc3465d0a7)
