### ISSUE TITLE
Launch of Bangalore: DesignUP! Article.

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#137]
The Bangalore event section needs populating with: https://opendesign.ushahidi.com/bangalore-designup-2019

- [ ] Information about the conference and where they can sign-up/attend

- [ ] Information about our purpose there

- [ ] Information about the intended workshop framework

**Comment by Erioldoesdesign** [comment]
You can find the workshop info here:
https://drive.google.com/open?id=1_G29c0eXw2tESLIl0ClYk89LzmHzdWiX5adJLZweubE

Design Up!'s info here: https://designup.io/blr2019/masterclasses/#tab-eriol-fox-creating-impact-with-open-source-and-humanitarian-tech-257

We'll need an overview of the event, what we want to happen there (based off the workshop framework) and the TenFour issues we'll focus on and how we're applying the Methodology to the workshop. 

A link out to the conference to buy tickets would be good traffic pointing but also a link to our socials that people can follow along with if they can't attend.

**Comment by deaduramilade** [comment]
https://docs.google.com/document/d/1O-DpXmL4n3SrQ9pggkTM4fSwSMDd-7R1BDyqVZ7L-iI/edit?usp=sharing

**Comment by Erioldoesdesign** [comment]
Approved :) closing out
