### ISSUE TITLE
Facebook Event Banner for cheltdesignfestival.org

### ISSUE THREAD

**Issue by thesocialdetail** [ushahidi/opendesign#140]
Facebook event banner image to promote the Cheltenham Design Event 
Size: 1920 x 1080 pixels 
Format: PNG or JPG 
Resources: 
Master Adobe Xd file - https://drive.google.com/open?id=1aKhyOOCgzjxq-gEvH_eM1XlJxlCgN-Sn
Approved photos: https://drive.google.com/drive/folders/1Nf-IeSDUm_Tw2WPcBd6ROWbFetmDwp9a?usp=sharing

Needs to have 
- our logo 
![Open-Design-Logo](https://user-images.githubusercontent.com/50371469/65875646-9748e780-e37f-11e9-944c-2090f0a1c531.png)

- location: Cheltenham, UK
- Date: 3rd Nov

Nice to have 
- their logo https://www.dropbox.com/sh/1t8xhvmyoo0gvuk/AADGKLL6D5OQSZ6Ztj6JO7C0a?dl=0

**Comment by Erioldoesdesign** [comment]
Might want a folder of resources? Ours on the google drive should be all open

**Comment by thesocialdetail** [comment]
No longer required
