### ISSUE TITLE
Duplicated text on methodology page 

### ISSUE THREAD

**Issue by thesocialdetail** [ushahidi/opendesign#141]
https://opendesign.ushahidi.com/methodology/

Are numbers 1 and 2 meant to be the same? Which should be deleted?

![Screenshot 2019-09-30 at 13.20.28.png](https://images.zenhubusercontent.com/5d2f38a1bcefe90a8aeb0e72/ed98e0cf-f4a6-4f26-bceb-ff0d18fc38d9)

**Comment by Erioldoesdesign** [comment]
Good spot!

**Comment by Erioldoesdesign** [comment]
Done!
