### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by aschwersenz** [ushahidi/opendesign#17]
What about SEO? Is that an issue?

**Comment by aschwersenz** [comment]
from Justin: Content person will have to handle SEO with guidance from anyone who can help

**Comment by aschwersenz** [comment]
from Jay: I neither think we have the budget, content, nor the property for a proper SEO (content) strategy and implementation. We’re running based on social and references from friends & family, plus media (if we’re lucky).

We’re not necessarily running based on organic search (that might be a phase 2 component but we could simply run paid media and it would probably be cheaper than a proper SEO strategy. Just my 2 cents.).

**Comment by aschwersenz** [comment]
from Eriol: SEO optimisation should really be considered in any content piece (but its not because we aren't all experts)

SEO strategy and PPC is a whole other beast that I would not expect our content/writer to undertake

**Comment by Erioldoesdesign** [comment]
@thesocialdetail @deaduramilade When we start adding in content to the website I'll lean on you both for SEO optimisation etc.

**Comment by thesocialdetail** [comment]
The [Yoast](https://yoast.com/wordpress/plugins/seo/) plugin will help with this in the start, once the keywords have been agreed. My suggestions are 
open source design
open source 
open design

**Comment by Erioldoesdesign** [comment]
Sound like good keywords to start with :)

@klickass @thomaskueber any other suggestions on keywords? We're syncing with Adobe content & Designit content on this too.

**Comment by thesocialdetail** [comment]
Not able to use Yoast as it is not able to read the page content, I think the solution requires code https://kb.yoast.com/kb/error-text-contains-0-words/

**Comment by Erioldoesdesign** [comment]
@aschwersenz I think the above comment from Joy will require you to look at Andreas

**Comment by deaduramilade** [comment]
Agree with Joy on the keywords. I'll be writing the articles with SEO and keyword optimization in mind

**Comment by Erioldoesdesign** [comment]
@thesocialdetail Just flagging, The Designit team will not be able to look at this until the week of the 5th at the earliest. Just wanted to give you an update :(

**Comment by Erioldoesdesign** [comment]
The bug with yoast is described in this issue now so I'm closing this one which was about the Yoast set up: https://github.com/ushahidi/opendesign/issues/58
