### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by aschwersenz** [ushahidi/opendesign#18]
For visitors from the EU we probably need all that GDPR stuff? Do you already have some legal texts for that? < Legal text is covered in the page: https://opendesign.ushahidi.com/privacy-policy/

Further dev work needed to make the following checkbox a validation requirement:

![Screenshot 2019-07-29 at 20.48.23.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/b88631c0-d998-4247-a847-1c43518546d0)

When a user tries to input their email address, the must check the checkbox to agree to the Privacy policy & terms located on:https://opendesign.ushahidi.com/privacy-policy/

If a user tries to submit an email address without checking the box it should throw an error to the user to ask them to check the box.

![Screenshot 2019-07-30 at 01.03.08.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/9f1da4bc-7750-4cf6-8225-aa8324486b2a)

**Comment by aschwersenz** [comment]
from Justin: It'll have to be GDPR compliant, yes. We have some boilerplate for that I think.

**Comment by Angamanga** [comment]
@Erioldoesdesign I have updated the form and made the checkbox required. The error-message does not look like in the designs though, that requires more customisations. Now it looks like this (in various browsers and mobile):
![IMG_C8FA1DDD3B17-1.jpeg](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/2caf9d7b-8fce-49db-92fe-de2cb0a7a8f0)![Screenshot 2019-08-01 at 14.12.13.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/8ecc1765-0225-43be-a5ad-4cbe203802e9)![Screenshot 2019-08-01 at 14.08.06.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/d04876a9-b0c8-481c-b323-91772ffd99e6)

Hopefully unblocks launch and then we can look into styling later.

**Comment by Erioldoesdesign** [comment]
This has been QA'd by a few various people and the bugs are inconsistent so I'm happy closing this!

I'll create an improvement ticket re. error styling that's like a P4.

THANKS ANNA YOU ROCK
