### ISSUE TITLE
Social media plan  #1

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#26]
First round of launch social posts via Joy

**Comment by Erioldoesdesign** [comment]
WIP document located here ready for feedback via comments: https://docs.google.com/document/d/1eWwhPGi8_rRaW-i0t6sSHF3PueNHkJlmQav05cBJSnA/edit?usp=sharing

**Comment by thesocialdetail** [comment]
The updated plan will continue to change as the project develops >
https://docs.google.com/presentation/d/10TY67_rHr2WaegGudJyyvQ5xGu1E-ilGFu22dZWdjZo/edit?usp=sharing

**Comment by vbhv** [comment]
Can someone please post a link to the new document?

**Comment by thesocialdetail** [comment]
completed
