### ISSUE TITLE
Methdology #1

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#30]
The first version of the Methodology to test at the 1st event

WIP Document here: https://docs.google.com/document/d/136xY-e6Vrr6Fes0t19Jh64qUbzes7TNsQrK7fncuimA/edit?usp=sharing

## Update: 
Methodlogy has been reviewed, amended and split into two:

1 - The public-facing replicable document that serves as a 'guide': https://docs.google.com/document/d/136xY-e6Vrr6Fes0t19Jh64qUbzes7TNsQrK7fncuimA/edit?usp=sharing

2 - The internal document intended to help guide or research gathering insight: https://docs.google.com/document/d/1lkaq7VA3INTwh4M941KYt-IQ-whhWm7W9k5cm436UDw/edit?usp=sharing

**Comment by Erioldoesdesign** [comment]
@klickass @vbhv  @thomaskueber this is what we'll be looking at in the meeting today: https://docs.google.com/document/d/136xY-e6Vrr6Fes0t19Jh64qUbzes7TNsQrK7fncuimA/edit?usp=sharing

There is still some work needed on this....especially in the area 'Specific methods employed' where the ways in which we're capturing research to inform further iterations of the methodology are concerned.

Also the workshop framework:
https://docs.google.com/document/d/1TOt3SK3Y8gHXdP0XE7FcSOAezHdYpBLvOUQF-jrjB5M/edit#heading=h.b5iwm5ybke0x

There's some (intended) duplication across these documents.

**Comment by klickass** [comment]
Did a pass on the methodology. Still have to do a pass on the framework.

**Comment by klickass** [comment]
Is the workshop framework ready for review @Erioldoesdesign?  /@thomaskueber

**Comment by Erioldoesdesign** [comment]
@klickass 😬 alas! not yet! by Wednesday for sure

**Comment by klickass** [comment]
No pressure

**Comment by Erioldoesdesign** [comment]
Newest version ready for final review :)

**Comment by Erioldoesdesign** [comment]
Methodlogy has been reviewed, amended and split into two:

1 - The public-facing replicable document that serves as a 'guide': https://docs.google.com/document/d/136xY-e6Vrr6Fes0t19Jh64qUbzes7TNsQrK7fncuimA/edit?usp=sharing

2 - The internal document intended to help guide or research gathering insight: https://docs.google.com/document/d/1lkaq7VA3INTwh4M941KYt-IQ-whhWm7W9k5cm436UDw/edit?usp=sharing

**Comment by Erioldoesdesign** [comment]
Closing this ticket and uploading the public facing one to the website
