### ISSUE TITLE
Article on opening up a repo and why - Interview with David McNamara & Dale Zak

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#46]
Focussing on the kinds of information that would be most interesting and useful for designers regarding things like: 

- What a closed repo is
- What an open repo is
-The process development needs to consider when being open source
-Details that are important for designers to understand
- How to find out more information & engage with open source as a subject
- Any more key discoveries via the interviews

**Comment by deaduramilade** [comment]
https://docs.google.com/document/d/1QMJRPgiQC-fXQz6GwBjPGRfvpxK6SIZdLkXPJv2Ds5g/edit?usp=sharing

**Comment by deaduramilade** [comment]
Here's the link to interview notes https://docs.google.com/document/d/1K0EIFfbh1tEpbA39LLlsLgitWF2kcpXyOZfxHNHhvX8/edit?usp=sharing

**Comment by Erioldoesdesign** [comment]
Added in 1st and 2nd round of support and review :) this is almost ready to go!

@klickass FYI our second article.

**Comment by vbhv** [comment]
reviewed and posted my comments @Erioldoesdesign

**Comment by klickass** [comment]
Finally came to read it. LGTM!

**Comment by Erioldoesdesign** [comment]
@deaduramilade This is ready to be added into a page in the wordpress website :)

**Comment by deaduramilade** [comment]
I've added to wordpress already

**Comment by Erioldoesdesign** [comment]
@deaduramilade Ah I see it now :) Thanks!
