### ISSUE TITLE
Pull quote template

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#47]
Design template for pull quotes for social medias.

.psd or .xd format for @thesocialdetail to be able to edit/amend quickly for socials.

**Comment by Erioldoesdesign** [comment]
This is completed and here are the files. I have to have them in an google drive folder as they are over 15MB

https://drive.google.com/drive/folders/143F5GG03UZVJYU2XoWf40WkwvlewPlqn?usp=sharing

Also Github doesn't allow uploading of .xd files and that's a key problem for Open Design in general.

**Comment by Erioldoesdesign** [comment]
@thesocialdetail can you review these and let me know whether you're happy? :)

**Comment by klickass** [comment]
@Erioldoesdesign Is it intentional that the font for the logo differs from the one on the website?

**Comment by Erioldoesdesign** [comment]
@klickass it should be the same the font is called Inter and looks like this on the pull quote:

![Screenshot 2019-07-29 at 18.00.54.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/4f5ef6bd-0a86-4724-958a-c496ade78643)

and like this on the website header for me:

![Screenshot 2019-07-29 at 18.01.03.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/597403bb-d89a-476b-888e-90a5cec38562)

Can you screengrab what you see please?

**Comment by klickass** [comment]
![Screenshot 2019-07-29 at 17 02 18](https://user-images.githubusercontent.com/2110595/62059086-db562980-b222-11e9-9517-367c8734e9fc.png)

![Screenshot 2019-07-29 at 17 03 37](https://user-images.githubusercontent.com/2110595/62059095-e01add80-b222-11e9-931b-eb8d35ca4ce8.png)

**Comment by Erioldoesdesign** [comment]
Ah I know what's happening. People who don't have the inter font are seeing a default system font because of the font not being outlined in teh SVG. okay fixing.

**Comment by klickass** [comment]
@Erioldoesdesign Thought of a webfont issue but this is the actual SVG as it seems. (Console shows me some broken jquery reference but assuming this doesn't have anything to do with the font being off).

![Screenshot 2019-07-29 at 17 05 42](https://user-images.githubusercontent.com/2110595/62059238-1fe1c500-b223-11e9-8c63-9c10baef64d2.png)

**Comment by Erioldoesdesign** [comment]
Fixed the bug described above that moved into a new ticket #60

**Comment by Erioldoesdesign** [comment]
@thesocialdetail can you look at the graphics and approve please?

**Comment by thesocialdetail** [comment]
Perfect
