### ISSUE TITLE
Investigate the back-end Wordpress template code

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#49]
Investigate and write documentation on how the Wordpress back-end template code is built so that we can understand how to build new block/modules/content styles in the website.

Code for the wordpress website as of July 2019 is located here: https://github.com/ushahidi/opendesign-website

We need to keep this repo/website source code untouched in case of rollback.

**Comment by Erioldoesdesign** [comment]
@Angamanga Do you feel like this could be closed? did you get to look at the code?

**Comment by Angamanga** [comment]
@Erioldoesdesign I have briefly skimmed it so lets close. I'll take closer look if needed later on :)
