### ISSUE TITLE
Article on Methodology & workshop framework

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#53]
An article that focuses on summarising and promoting the 1st round of methodology and workshop framework that builds up to the events. 

The first and second events are confirmed as Cheltenham #130 and Bangalore #129

Third event is pending for Nairobi #131

The methodology document is here: https://docs.google.com/document/d/136xY-e6Vrr6Fes0t19Jh64qUbzes7TNsQrK7fncuimA/edit?usp=sharing

Workshop Framework here: https://docs.google.com/document/d/1TOt3SK3Y8gHXdP0XE7FcSOAezHdYpBLvOUQF-jrjB5M/edit?usp=sharing

~Note: This article cannot be started until the 1st draft of the Methodology & workshop framework is approved by the team~

Both documents are now approved by the team.

Can you please read through the documents and present what you think is best? A summary of the events? Key info? A promo piece with a call to action focused on signing up for the mailing list?

**Comment by deaduramilade** [comment]
I've read and reviewed both and I don't think a special article has to be done to "announce" them. I think they can be published as is. I see the methodology has been published on the website https://opendesign.ushahidi.com/methodology/

I think that's okay.

**Comment by Erioldoesdesign** [comment]
Awesome - sounds good lade! Closing this
