### ISSUE TITLE
Article: Our findings from our desk research & interviews

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#54]
A short article focusing on the biggest learnings from our desk research/interviews with design genius.

To be largely taken from our notes on the interviews, trello board of answers to the questions about open design as well as the methodology.

https://trello.com/b/CVSlRaj8/open-design-questions
https://docs.google.com/document/d/1m4D9mV5dPAoF5-cieS81SEN4LWbuDzQaKBTADlIY-ks/edit?usp=sharing
https://docs.google.com/document/d/136xY-e6Vrr6Fes0t19Jh64qUbzes7TNsQrK7fncuimA/edit?usp=sharing

**Comment by deaduramilade** [comment]
https://docs.google.com/document/d/1qz0W4EwmmvJJz3bG0HZV5IrxpxUExEdEjJ88Vm7uAPs/edit?usp=sharing draft ready

**Comment by Erioldoesdesign** [comment]
@thomaskueber @klickass Ready for us to review

**Comment by Erioldoesdesign** [comment]
@vbhv Ready for review

**Comment by klickass** [comment]
Reviewed and suggested quite a couple of edits. Added formatting to transform this into more of a "guide"/fact sheet, which also makes this piece easier to read. Love the style and language but believe we have to work on using easier language.

**Comment by deaduramilade** [comment]
Updated

**Comment by Erioldoesdesign** [comment]
Split the article into two:

1.https://docs.google.com/document/d/1qz0W4EwmmvJJz3bG0HZV5IrxpxUExEdEjJ88Vm7uAPs/edit?usp=sharing

2. https://drive.google.com/open?id=1aC1UN3IW9dtQnrXBPxYvNGR_DqCU30h8pDHNDQaCZck

These are ready for re-review

**Comment by Erioldoesdesign** [comment]
@klickass @thomaskueber

**Comment by Erioldoesdesign** [comment]
I've included these in the backend of wordpress.
