### ISSUE TITLE
Button block for wordpress website

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#55]
The wordpress website doesn't currently have a block that is a button solo. There are templates for text + button.

Current button styles:
![Screenshot 2019-07-23 at 10.19.53.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/9241f883-d498-46a0-95e4-6cb260d57003)
![Screenshot 2019-07-23 at 10.19.44.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/a8e9fcc4-1d49-4eef-a2dd-35f6499d9666)

![Screenshot 2019-07-23 at 10.22.02.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/ed5e7c86-e1f5-452e-8846-ec54ad04c370)

We should look at blocks

Short text + button full width

Short text x2 + button x 2 - 2 columns

Short text x3 + button x 3 - 3 columns

button x 2 - 2 columns

button x 3 - 3 columns

New design layouts for buttons to be used across pages/posts:

![Button layouts](https://user-images.githubusercontent.com/11681324/63166279-d7e5df00-c025-11e9-9b89-1ad9b1d34e09.png)

**Comment by sethburtonhall** [comment]
@Erioldoesdesign you mentioned that you would like these blocks to be reusable throughout the site ... but where specifically do you need them on the site?

**Comment by Erioldoesdesign** [comment]
So I want to be able to use buttons across other pages in the site. So at the moment we have 3 pages:

Home: https://opendesign.ushahidi.com/
Article 1: https://opendesign.ushahidi.com/design-should-be-open-for-all/ (which is actually using a page template and not a post)
Privacy policy: https://opendesign.ushahidi.com/privacy-policy/

I'd like to be able to use buttons across pages and posts

**Comment by Erioldoesdesign** [comment]
Issue updated with button styles/layouts regarding columns
