### ISSUE TITLE
**BUG** Unable access SEO with Yoast 

### ISSUE THREAD

**Issue by thesocialdetail** [ushahidi/opendesign#58]
Yoast reports the pages as not having any content. 
Solution
Add content to the default editor and the word count will update automatically.> 
https://kb.yoast.com/kb/error-text-contains-0-words/

This issue is the bug from https://github.com/ushahidi/opendesign/issues/17

**Comment by Erioldoesdesign** [comment]
@aschwersenz

**Comment by Angamanga** [comment]
@Erioldoesdesign This is fixed now so Yoast is ready to be used. I have not added any keywords or done any other config than fixing the error with pages not having content. Let me know if you want that fixed too :).

**Comment by Erioldoesdesign** [comment]
@thesocialdetail can you confirm this is fixed for your workflow plz?

**Comment by thesocialdetail** [comment]
Working and added keywords
