### ISSUE TITLE
Mailchimp signup form on facebook

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#59]
https://mailchimp.com/help/add-or-remove-a-signup-form-on-your-facebook-page/?_ga=2.166289790.1983008573.1563954414-1959942594.1563954414

Let's try and get a signup form embedded into our facebook page.

**Comment by thesocialdetail** [comment]
Cool, I will need access to the MailChimp. To confirm: the aim would be to collect details only to email people about the events right or will we be starting a newsletter?

**Comment by Erioldoesdesign** [comment]
@thesocialdetail emailing about events. The CTA is 'Join the movement' so it's intentionally broad.

We identified early on that while a newsletter would be great, it's a lot of work to maintain and we don't really want to re-hash content from other sources like many other projects do

**Comment by Erioldoesdesign** [comment]
Sending @thesocialdetail Mailchimp login details via DM

**Comment by thesocialdetail** [comment]
Added to the FB page, had to edit the form view to hide the HTML options.
