### ISSUE TITLE
**BUG** Font is not outlined in the logo SVG and displaying differently for people without the inter as a system font.

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#60]
![62059095-e01add80-b222-11e9-931b-eb8d35ca4ce8.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/52b6daa3-9810-49ce-930e-3ea122c9df85)

![62059238-1fe1c500-b223-11e9-8c63-9c10baef64d2.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/d6f37c8f-232f-4bc3-b47b-f59bd3f0a644)

Logo displays as a different font due to the SVG not being expanded.

**Comment by Erioldoesdesign** [comment]
@klickass can you test again please?

**Comment by klickass** [comment]
MIght be some server side caching (used a different browser) as I am still seeing the same problem @Erioldoesdesign

**Comment by Erioldoesdesign** [comment]
Okay - I'm gonna try uploading via a different file name as sometimes Wordpress doesn't like you using the same file name for versions of files

**Comment by Erioldoesdesign** [comment]
Fixed :D:D:D
