### ISSUE TITLE
Points from the first blog to add to the highlight story for Facebook

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#61]
Use the Launch article to inform a highlight story on Facebook

https://opendesign.ushahidi.com/design-should-be-open-for-all/

Use the master XD document to create visual assets for this work

XD Master file: https://drive.google.com/open?id=1aKhyOOCgzjxq-gEvH_eM1XlJxlCgN-Sn

**Comment by thesocialdetail** [comment]
done
