### ISSUE TITLE
Adobe's Article for their own blog and comms

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#63]
Aodbe asked us to answer several questions about the project via email.

Eriol's placed in a document here:

https://docs.google.com/document/d/1KDyxwc-bSSEZMjyb_7-L_OYQPVOs3A2nV6gSQO_IQEg/edit?usp=sharing

Eriol has asked for @aoduor 's input (mostly from an 'a-oking that I have communicated the right thing from an Ushahidi org perspective' 

@thomaskueber and @klickass it'd be good to make sure you also have visibility of Ushahidi's answers. But please be aware that Adobe asked to 'interview Ushahidi on the project' so it might be odd if we had too much detailed involvement from Adode (via Jay's perspective) and Designit's.

Also tagging @thesocialdetail for visibility on the TOV I'm taking

**Comment by Erioldoesdesign** [comment]
The first draft of these answers are complete and I'm going to notify Adobe via email that we're reviewing the answers internally.

**Comment by klickass** [comment]
Totally fine with the provided answers, nothing to add, found one glitch (left a comment)

**Comment by vbhv** [comment]
@Erioldoesdesign good to go!

**Comment by Erioldoesdesign** [comment]
Waiting on @aoduor to do a final approval for this and then we can push it to Adobe

**Comment by aoduor** [comment]
Looking good. Go for it

**Comment by Erioldoesdesign** [comment]
Sending the document to Adobe :D
