### ISSUE TITLE
Eventbrite banner template for the upcoming events 

### ISSUE THREAD

**Issue by thesocialdetail** [ushahidi/opendesign#64]
2160 x 1080px (2:1 ratio—twice as wide as tall) image that's no larger than 10MB

**Comment by Erioldoesdesign** [comment]
Banner variations:

![Eventbrite banner standard 1](https://user-images.githubusercontent.com/11681324/62196577-fb9ef900-b386-11e9-876e-3c3785c16ee5.png)
![Eventbrite banner standard 2](https://user-images.githubusercontent.com/11681324/62196578-fb9ef900-b386-11e9-8eb0-939d11335203.png)
![Eventbrite banner standard 3](https://user-images.githubusercontent.com/11681324/62196579-fb9ef900-b386-11e9-9b17-aa38e0b48caa.png)
![Eventbrite banner unique 1 – 1](https://user-images.githubusercontent.com/11681324/62196580-fc378f80-b386-11e9-8fc9-e06337170406.png)
![Eventbrite banner unique 1 – 2](https://user-images.githubusercontent.com/11681324/62196581-fc378f80-b386-11e9-8848-a144f505733c.png)
![Eventbrite banner unique 1](https://user-images.githubusercontent.com/11681324/62196582-fc378f80-b386-11e9-9c7e-d9477aba4b86.png)


Re-uploading the master doc with the editable canvases:

https://drive.google.com/open?id=1aKhyOOCgzjxq-gEvH_eM1XlJxlCgN-Sn

**Comment by Erioldoesdesign** [comment]
I went with a few 'event' specific texts/titles in the last one.

Please let me know what you think @thesocialdetail

**Comment by thesocialdetail** [comment]
The events related ones will work great. when we confirm the location 100%, could the location detail be added to the design? @Erioldoesdesign

**Comment by Erioldoesdesign** [comment]
@thesocialdetail Yes! I'll add to the master XD file now because I thought of a cute way to do that!

**Comment by Erioldoesdesign** [comment]
Please tell me whether you think this is as adorable as I think it is:

![Eventbrite banner unique 1 – 1](https://user-images.githubusercontent.com/11681324/62206743-2abf6580-b39b-11e9-8d1f-dd643b8e34fd.png)
![Eventbrite banner unique 1 – 2](https://user-images.githubusercontent.com/11681324/62206744-2abf6580-b39b-11e9-9f59-947f0e14385e.png)
![Eventbrite banner unique 1](https://user-images.githubusercontent.com/11681324/62206747-2abf6580-b39b-11e9-9090-e05d4e32084d.png)

**Comment by Erioldoesdesign** [comment]
Folder location for .PNGs

**Comment by klickass** [comment]
Recommending to…

- reduce contrast/opacity for the bkgnd images by 10 or 20%, just to flat them out a bit more
- move down the image with Thomas to get more faces in the view
- add "Seattle, USA" wherever applicable (as it happened so why not use it)
- do something to make the red dot in our logo visible

**Comment by Erioldoesdesign** [comment]
reduce contrast/opacity for the bkgnd images by 10 or 20%, just to flat them out a bit more
move down the image with Thomas to get more faces in the view
^^^ I can do this that's fine


add "Seattle, USA" wherever applicable (as it happened so why not use it)
These banners are for events that are going to happen, not that have happened in the past.

do something to make the red dot in our logo visible
I'm not sure what I can do here that doesn't change the brand logo/styling of all banners and would require me to update all banner templates.

**Comment by thesocialdetail** [comment]
I am happy with the addition of the location. Think they are good to go.

**Comment by Erioldoesdesign** [comment]
Updated the .pngs with Jay's suggestions located in here: https://drive.google.com/drive/u/1/folders/18m96zggPF4iSAKDOMT8ceYtBKYfUfsFx

![Eventbrite-banner-London.jpg](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/faef296b-1b53-416f-b0c3-e35abe9682cc)![Eventbrite-banner-Berlin.jpg](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/89b77bf6-cc67-4203-af98-4dd27d930b11)![Eventbrite-banner-Nairobi.jpg](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/7e92540f-a017-43cd-888e-83fd498bd8d9)![Eventbrite-banner-standard-1.jpg](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/cbeb6e22-7f8b-4023-bd49-edffaa6bd108)![Eventbrite-banner-standard-2.jpg](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/bfb798db-7664-4722-8154-948a7f2de5ac)[Uploading... Eventbrite-banner-standard-3.jpg ]
