### ISSUE TITLE
Add Facebook pixel to website code

### ISSUE THREAD

**Issue by thesocialdetail** [ushahidi/opendesign#65]
Find the <head> </head> tags in your web page code, or locate the header template in your CMS or web platform. 

Paste the pixel code at the bottom of the header section, just above the </head> tag. Facebook pixel code can be added above or below existing tracking tags (such as Google Analytics) in your site header.

<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '471922456707221');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=471922456707221&ev=PageView&noscript=1"
/></noscript>

**Comment by Erioldoesdesign** [comment]
I think we put this code here:

<img width="1100" alt="Screenshot 2019-07-31 at 11 55 35" src="https://user-images.githubusercontent.com/11681324/62198472-5dad2d80-b38a-11e9-9269-9dc1eb330ef2.png">

**Comment by thesocialdetail** [comment]
Forgot to close this last night mange to set it up using a plugin. Just checked its received 8 hits so up and working.
