### ISSUE TITLE
GDPR check box for Mailchimp form on Facebook 

### ISSUE THREAD

**Issue by thesocialdetail** [ushahidi/opendesign#68]
On the Mailchimp form, there should be a way to add an opt-in option which will then appear on the facebook tab. If not we can create a new form just form Facebook signups. Need t look more into this

**Comment by Erioldoesdesign** [comment]
This was solved by @Angamanga in a separate bug issue....not sure why this one exists so closing as it's a duplicate.

**Comment by Erioldoesdesign** [comment]
@thesocialdetail can you provide a link to the facebook implementation and a series of screenshot for the issue describing what you need from a developer (if anything?)

**Comment by thesocialdetail** [comment]
@Erioldoesdesign I think its something that needs to be changed in Mailchimp

To submit to the newsletter on Facebook the form comes up 
https://www.facebook.com/OpenDesignIs/app/100265896690345/

but I can't find a way in Mailchimp to add a GDPR question

![Screenshot 2019-08-15 at 17.22.11.png](https://images.zenhubusercontent.com/5d2f38a1bcefe90a8aeb0e72/6d9ed88b-896a-4305-8680-044226fb459f)

**Comment by Erioldoesdesign** [comment]
@thesocialdetail ah I see...I think I can look at this in mailchimp
I'll take a look now

**Comment by Erioldoesdesign** [comment]
Fixed this @thesocialdetail ;)
https://www.facebook.com/OpenDesignIs/app/100265896690345/

I had to use the text space at the top available in the layout to link the Privacy Policy and add the supplementary text. If you want some changes let me know or I can show you where to edit in the Mailchimp.
