### ISSUE TITLE
Live tweet from FOSS4G Bucheres

### ISSUE THREAD

**Issue by thesocialdetail** [ushahidi/opendesign#69]
Twitter take over while you are at the conference 
Key tips
- Use the event hashtag if they have it 
- sign of the tweets with " EF" or your name to make more personal

Wish list
- Pictures or video of you on stage

This request if only able to

**Comment by klickass** [comment]
Please keep a laser focus to the OSD target audience (use easy language, tailor to non-code-savvy designers) and prevent setting precedence/opening doors for OT discussions or debates around F/OSS. And have a ton of fun @Erioldoesdesign!

**Comment by Erioldoesdesign** [comment]
Tweets can be seen here : https://twitter.com/opendesignis/status/1168506454388727808

**Comment by klickass** [comment]
Great stuff!
