### ISSUE TITLE
'Witness' brief  for events

### ISSUE THREAD

**Issue by thesocialdetail** [ushahidi/opendesign#70]
As we will be approaching people to speak at the event about their experience of a crisis thought it would be good to have a doc outlining what we would like to for them.

https://docs.google.com/document/d/1CVkht7rt2_cOUrYfaY4c5ekjgyzwiHFdRRM6cJy-020/edit?usp=sharing

**Comment by Erioldoesdesign** [comment]
If we want to engage with Grenfell then we have to consider the potential complexities of the event laid out here: https://grenfellactiongroup.wordpress.com/

There are several groups and individuals involved in the aftermath but intentions are largely unclear.

Grenfell action group
Grenfell United
Grenfell Community Response and Support
Housing Action Southwark & Lambeth
Justice4Grenfell

And of course the local council authorities
