### ISSUE TITLE
Create Eventbrite for London 28th Sept

### ISSUE THREAD

**Issue by thesocialdetail** [ushahidi/opendesign#71]
Question to ask 
- Do you have any Food and allergies 
- Accessibility of the event

This is an all-day event, however, you will be required to also complete design sprint (link to what it is). 
 - Are you able to commit a min of 10-hour remote work after the event? 
Do you have the following 
- A Laptop
Download Adobe XD 
Download Mural on to your phone 

Tickets types 
1 The Researcher or UX 
2 Visual Designer or UI or Graphic Designer 
3 Interaction Designer 
4 Project Manager or Design Lead or Scrum master
5 Wire Framing or Prototyping 
Team ticket

**Comment by Erioldoesdesign** [comment]
Notes: Beginner - Advanced

Design job title - 'Other'

**Comment by thesocialdetail** [comment]
Close as event did not happen.
