### ISSUE TITLE
small grammatical error on the website

### ISSUE THREAD

**Issue by danisyellis** [ushahidi/opendesign#86]
Hi all. So excited you're doing this!
I just wanted to let you know about a small grammatical error on the homepage. 

In the color-changing square, you say "Non-profit's need open source." The apostrophe makes it possesive, but you just want a normal plural. It should read: "Non-profits need open source."

I didn't see a public repo for the website. If I'm wrong, let me know and I can make the change and send a PR.

**Comment by Erioldoesdesign** [comment]
@vbhv think you could look into this change?

**Comment by vbhv** [comment]
@Erioldoesdesign is this for me to do? Can you provide the link to the admin page. I have my password and I need to try it out.

**Comment by Erioldoesdesign** [comment]
@vbhv http://opendesign.ushahidi.com/admin

**Comment by vbhv** [comment]
I've made the changes.

**Comment by Erioldoesdesign** [comment]
Thank you @vbhv :D
