### ISSUE TITLE
What is success for an article?

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opendesign#90]
From your experience, what means 'success' for a piece of written content?

e.g. Shares of articles, comments, people writing response articles, getting people involved.

**Comment by Erioldoesdesign** [comment]
@deaduramilade Any progress on this?

**Comment by deaduramilade** [comment]
I'll create an issue for "adding sign up box on all pages"

**Comment by Erioldoesdesign** [comment]
Added these to the rough KPI document: https://docs.google.com/document/d/12dSe9hGbsNA1KFGmXNiUSAZUjkwgDo4vSQ4OHehJXNI/edit?usp=sharing

closing out
